---
- name: Delete IaC-webserver
  hosts: localhost
  connection: local
  tasks:
    - name: Remove a VM and all resources that were autocreated
      azure_rm_virtualmachine:
       resource_group: jenkins_group
       name: IaC-webserver
       remove_on_absent: all_autocreated
       state: absent
- name: Create Azure VM
  hosts: localhost
  connection: local
    
  tasks:
      # Creating a Resource Group
    - name: Create resource group
      azure_rm_resourcegroup:
          name: jenkins_group
          location: westeurope
    # Creating a Virtual Network
    - name: Create virtual network
      azure_rm_virtualnetwork:
          resource_group: jenkins_group
          name: vnet-web
          address_prefixes: "10.0.0.0/16"
    
    # Add a subnet
    - name: Add subnet
      azure_rm_subnet:
          resource_group: jenkins_group
          name: snet-web
          address_prefix: "10.0.2.0/24"
          virtual_network: vnet-web
    
    # Add a public IP
    - name: Create public IP address
      azure_rm_publicipaddress:
          resource_group: jenkins_group
          allocation_method: Static
          name: pip-web
      register: output_ip_address
        
    - name: Output public IP
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"
    
    # Creating a Network Security Group
    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: jenkins_group
        name: nsg-web
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          
          - name: HTTP
            protocol: Tcp
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 1002
            direction: Inbound
               
     # Create a Virtual Network Interface Card
    - name: Create a network interface
      azure_rm_networkinterface:
          name: nic-web
          resource_group: jenkins_group
          virtual_network: vnet-web
          subnet_name: snet-web
          security_group: nsg-web
          public_ip_name: pip-web
            
     # Creating a VM
    - name: Create VM
      azure_rm_virtualmachine:
         resource_group: jenkins_group
         name: IaC-webserver
         vm_size: Standard_DS1_v2
         admin_username: ansadmin
         admin_password: Iac4nsPaswd!
         network_interfaces: nic-web
         os_type: Linux
         image:
           offer: CentOS
           publisher: OpenLogic
           sku: '7.5'
           version: latest

- hosts: dev-server
  become: True
  tasks:
    - name: Install python3 pip
      yum:
        name: python3-pip
        state: present
    
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
        
    - name: Remove Podman (conflict docker)
      yum:
        name: podman
        state: absent
    
    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
        
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
    
    - name: Start the container
      docker_container:
        name: iacproject
        image: "sh4rks/iacproject:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
