- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: dev-server-RG
      location: westeurope

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: dev-server-RG
      name: devserverVnet
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: dev-server-RG
      name: devserverSubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: devserverVnet

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: dev-server-RG
      allocation_method: Static
      name: dev-server-pubip
      domain_name: iacprojectteam1
    register: output_ip_address

  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."

  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: dev-server-RG
      name: webserverNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1002
          direction: Inbound
        - name: HTTP
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 1001
          direction: Inbound

  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: dev-server-RG
      name: webserverNIC
      virtual_network: devserverVnet
      subnet: devserverSubnet
      public_ip_name: dev-server-pubip
      security_group: webserverNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: dev-server-RG
      name: dev-server
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFIHMFirbqnrINNfLBfyNpYVrE0hwPgzYY6kuP3YDIT3FAF8Zqkzmq+KrwEH8O8Rx+LfCeRf4NOz/8AZPdv4f+tMY5o61tqU2G6+zZLgkw7lCfjrLRr6duAs6Rg/BDxRWHPOwp8YJI3/LJ1+cBRD4/Q/s8Fv3ACkmoGmx2KjnhxsGL69GZHjF+RFAVyTNgFKRy+3uxLHDh7syTXdCwF+bIkcp9uKHfmxq6muvLVcm8U9tztWa9TnOQuAYvHDe19XNvF7iagpn9LqVASxWZbSrqsKYwhsIcbE7sVJWOKZ8qXgZjnb/9Uk5D6WyHkXKJVpEb7ZYNweZpemzXIlTEgIUB azureuser@azure
      network_interfaces: webserverNIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
